name: nix-test

# Configures this workflow to run every time a change is pushed to the branch called `master`.
on:
  push:
    branches: ['master']
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out the package
    - uses: actions/checkout@v2
    - name: Cache install Nix packages
      uses: mtoohey31/cache-flake-attrs@v2
      with:
        key: ${{ runner.os }}-nix-${{ hashFiles('./flake.lock', './flake.nix') }}

    # Build the package defined in the Nix Flake 
    - name: Build the derviation defined in the Nix Flake
      run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build .#nix-flake-docker
